name: CI/CD

on:
  push:
    branches:
      - main  # Déclenche seulement sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Utiliser la dernière version

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t eudemonia01/car-service:latest backend/car-service/

      - name: Push Docker Image
        run: |
          docker push eudemonia01/car-service:latest
