name: CI/CD
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker Images
        run: |
          docker build -t eudemonia01/car-service:latest backend/car-service/
          docker push eudemonia01/car-service:latest
